<?xml version="1.0" encoding="utf-8"?><Database Name="AMSDB" Class="AMSDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\AMSDB.mdf;Integrated Security=True" SettingsObjectName="Asset_Management_System.My.MySettings" SettingsPropertyName="AMSDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Asset" Member="Assets">
    <Type Name="Asset">
      <Column Name="Id" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Manufacturer" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Asset type]" Member="Asset_type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Model" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Serial number]" Member="Serial_number" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Condition" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Inventory location]" Member="Inventory_location" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[Date of acquisition]" Member="Date_of_acquisition" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Vendor" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Value At Acquisition]" Member="Value_At_Acquisition" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Invoice" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WarrantyId" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AssetType" Member="AssetTypes">
    <Type Name="AssetType">
      <Column Name="Id" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.InventoryLocation" Member="InventoryLocations">
    <Type Name="InventoryLocation">
      <Column Name="Id" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Name ]" Member="Name_" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Manufacturer" Member="Manufacturers">
    <Type Name="Manufacturer">
      <Column Name="Id" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>